### PR TITLE
Extended to support R3 as well

### PR DESCRIPTION
**Pull request by darvasd**
Extended to support Restaurant 3 too for the guys in Prévessin. Also, the currency can now be defined per restaurant (as prices are in EUR for R3, but in CHF for the other two restaurants).

See it working here: http://r3d2.herokuapp.com/monday

### CODE REVIEW

**Comment by kdungs** [comment]
Wow this is awesome! Thanks a lot! I didn't expect anyone to take interest in this. :) What do you think about using the UTF-8 euro sign € instead of EUR?

Otherwise LGTM.

P.S. Really hope my hacky code didn't cause too much frustration. :)

**Comment by darvasd** [comment]
Sure, let's go for €, why not? I've replaced EUR with €.

Actually, I was looking for something completely different and I've found R1D2 by chance. But I always wanted to write a script that e-mails me the menu every day before lunchtime. :)
Despite the fact that I don't master any of the used technologies, it was fairly quick and easy to understand and extend your code, so kudos for your code.

**Comment by kdungs** [comment]
Haha thanks! Reverse engineering the Novae website was a huge pain in the backside… :)

:shipit:

**Comment by kdungs** [comment]
All integrated and the Telegram bot is running again (nobody told me it was broken, seemed to have lost its webhook :/). It's a shame R3 doesn't have names on the dishes…

Again thanks a lot for this PR! :cake:

**Comment by darvasd** [comment]
Thanks!

There were dish names on the R3 website until last week, so hopefully this is just some summer transient problem.

**Pull request merged**
